version: 2

models:
  - name: stg_green_tripdata
    description: "Staging model for green taxi trips"
    columns:
      - name: vendorid
        data_tests:
          - not_null
      - name: pickup_datetime
        data_tests:
          - not_null
      - name: payment_type
        description: "Payment method"
        data_tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]

  - name: stg_yellow_tripdata
    description: "Staging model for yellow taxi trips"
    columns:
      - name: vendorid
        data_tests:
          - not_null